kitOnJoin:
  enabled: false
  kitName: starter
kitsCMD:
  # Enable /kits command it is disabled by default to avoid conflicts with other plugins
  enabled: false
databases:
  databaseType: "h2"
  h2:
    database: xPlayerKits
  mysql:
    host: localhost
    port: 3306
    database: xPlayerKits
    user: admin
    password: 123456
  mongodb:
    host: localhost
    port: 27017
    database: xPlayerKits
    user: admin
    password: 123456
migrate:
  mysql:
    host: localhost
    port: 3306
    database: xPlayerKits
    user: admin
    password: 123456