name: XPlayerKits
main: io.github.InsiderAnh.xPlayerKits.PlayerKits
version: 1.0.0
author: InsiderAnh
api-version: 1.13
folia-supported: true
depend:
  - PlaceholderAPI
commands:
  xkits:
  kits:
permissions:
  xkits.admin:
    description: "Allow use /xkits editor."
  xkits.countdown.bypass:
    description: "Allow to bypass countdown of kits."