name: XPlayerKits
main: io.github.InsiderAnh.xPlayerKits.PlayerKits
version: 2.0.7
author: InsiderAnh
folia-supported: true
depend:
  - PlaceholderAPI
commands:
  xkits:
    aliases:
      - xkit
permissions:
  xkits.admin:
    description: "Allow use /xkits editor."
  xkits.countdown.bypass:
    description: "Allow to bypass countdown of kits."